import os
from langchain_chroma import Chroma # Updated import
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_ollama import OllamaLLM # Updated import
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY

# --- Configuration ---
DB_PATH = "./chroma_db"
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
LLM_MODEL = "gemma4:e2b" 
OUTPUT_FOLDER = "./generated_notes"

if not os.path.exists(OUTPUT_FOLDER):
    os.makedirs(OUTPUT_FOLDER)

# --- THE STRICT STRUCTURE TEMPLATE ---
STRUCTURE_TEMPLATE = """
You must organize the notes using the following 7 sections EXACTLY. 
Do not skip any section. If the provided context doesn't have enough information for a section, use your general knowledge to fill it, but keep the section header.

1. Introduction
   - Definition of the topic
   - Purpose and core objective
   - Primary conversion/function (e.g., X to Y)

2. Working / Process
   - Step-by-step mechanism
   - Internal representations or methodologies
   - Core operational flow

3. Key Features
   - List of essential tools/capabilities
   - Specific technical components
   - Unique identifiers or analysis capabilities

4. Comparison / Analysis (e.g., Static vs Dynamic, or A vs B)
   - Contrast the primary approach with an alternative
   - Pros and cons of the current method
   - Context of when to use which

5. Advantages
   - Why is this tool/method used?
   - Specific benefits in industry or academia
   - Support and compatibility

6. Limitations
   - What are the weaknesses?
   - Common failure points or difficulties
   - Required expertise level

7. Conclusion
   - Summary of its importance
   - Industry status
   - Final verdict on its utility
"""

# --- REPORTLAB STYLING ENGINE ---
class PDFStylist:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        
        # Use UNIQUE names to avoid "Style already defined" error
        self.styles.add(ParagraphStyle(
            name='CustomMainTitle',
            fontName='Helvetica-Bold',
            fontSize=22,
            textColor=colors.darkblue,
            alignment=TA_CENTER,
            spaceAfter=20
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomSectionHeader',
            fontName='Helvetica-Bold',
            fontSize=14,
            textColor=colors.darkred,
            spaceBefore=15,
            spaceAfter=10
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBodyText',
            fontName='Helvetica',
            fontSize=11,
            textColor=colors.black,
            alignment=TA_JUSTIFY,
            leading=14,
            spaceAfter=10
        ))

        self.styles.add(ParagraphStyle(
            name='CustomMetaData',
            fontName='Helvetica-Oblique',
            fontSize=10,
            textColor=colors.grey,
            alignment=TA_CENTER,
            spaceAfter=20
        ))

def clean_text(text):
    """Removes problematic characters for ReportLab"""
    return text.replace('\u2013', '-').replace('\u2014', '-').replace('\u2022', '•')

def save_reportlab_pdf(content, filename, query):
    stylist = PDFStylist()
    doc = SimpleDocTemplate(os.path.join(OUTPUT_FOLDER, f"{filename}.pdf"), pagesize=A4)
    story = []

    # 1. Add Main Title
    story.append(Paragraph(clean_text(f"Academic Notes: {query}"), stylist.styles['CustomMainTitle']))
    story.append(Paragraph(clean_text("Generated by Gemma 4 Local RAG System"), stylist.styles['CustomMetaData']))
    story.append(Spacer(1, 12))

    # 2. Process the AI content
    lines = content.split("\n")
    for line in lines:
        line = line.strip()
        if not line: continue
        
        # Detect Section Headers (1. Introduction, etc.)
        if any(line.startswith(f"{i}.") for i in range(1, 8)):
            story.append(Paragraph(clean_text(line), stylist.styles['CustomSectionHeader']))
        elif line.startswith("- ") or line.startswith("* "):
            bullet_text = f"• {line[2:]}"
            story.append(Paragraph(clean_text(bullet_text), stylist.styles['CustomBodyText']))
        else:
            # Remove markdown bold ** and add to body
            text_cleaned = line.replace('**', '')
            story.append(Paragraph(clean_text(text_cleaned), stylist.styles['CustomBodyText']))

    doc.build(story)
    return os.path.join(OUTPUT_FOLDER, f"{filename}.pdf")

def generate_study_notes():
    embeddings = HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL_NAME)
    if not os.path.exists(DB_PATH): 
        print("Error: Run ingest.py first!")
        return
    
    # Updated Chroma import usage
    vectorstore = Chroma(persist_directory=DB_PATH, embedding_function=embeddings)
    
    # Updated Ollama import usage (OllamaLLM)
    llm = OllamaLLM(model=LLM_MODEL)

    print("\n--- 📝 ReportLab Structured Note Builder ---")
    questions_input = input("Enter the topics/questions you want notes for (separated by commas): ")
    questions = [q.strip() for q in questions_input.split(",")]

    for query in questions:
        print(f"\n🚀 Processing: {query}...")
        docs = vectorstore.similarity_search(query, k=5)
        context = "\n\n---\n\n".join([doc.page_content for doc in docs])

        prompt = f"""
        You are an expert academic writer. Create a highly structured study guide.
        
        STRICT FORMATTING REQUIREMENT:
        You must use the following 7-section structure exactly:
        {STRUCTURE_TEMPLATE}
        
        CONTEXT:
        {context}
        
        TOPIC: {query}
        
        Write the notes now. Use bullet points for lists.
        """

        response = llm.invoke(prompt)
        file_name = query.replace(" ", "_").replace("?", "").replace(",", "")
        try:
            path = save_reportlab_pdf(response, file_name, query)
            print(f"✅ Enterprise PDF Saved: {path}")
        except Exception as e:
            print(f"❌ Error saving {query}: {e}")

if __name__ == "__main__":
    generate_study_notes()
