import os
from langchain_community.vectorstores import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.llms import Ollama
from xhtml2pdf import pisa

# --- Configuration ---
DB_PATH = "./chroma_db"
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
LLM_MODEL = "gemma4:e2b" 
OUTPUT_FOLDER = "./generated_notes"

if not os.path.exists(OUTPUT_FOLDER):
    os.makedirs(OUTPUT_FOLDER)

# --- THE STRICT STRUCTURE TEMPLATE ---
# This forces the AI to follow your exact 7-point format
STRUCTURE_TEMPLATE = """
You must organize the notes using the following 7 sections EXACTLY. 
Do not skip any section. If the provided context doesn't have enough information for a section, use your general knowledge to fill it, but keep the section header.

1. Introduction
   - Definition of the topic
   - Purpose and core objective
   - Primary conversion/function (e.g., X to Y)

2. Working / Process
   - Step-by-step mechanism
   - Internal representations or methodologies
   - Core operational flow

3. Key Features
   - List of essential tools/capabilities
   - Specific technical components
   - Unique identifiers or analysis capabilities

4. Comparison / Analysis (e.g., Static vs Dynamic, or A vs B)
   - Contrast the primary approach with an alternative
   - Pros and cons of the current method
   - Context of when to use which

5. Advantages
   - Why is this tool/method used?
   - Specific benefits in industry or academia
   - Support and compatibility

6. Limitations
   - What are the weaknesses?
   - Common failure points or difficulties
   - Required expertise level

7. Conclusion
   - Summary of its importance
   - Industry status
   - Final verdict on its utility
"""

def get_html_template(content, query):
    return f"""
    <html>
    <head>
        <style>
            @page {{ size: A4; margin: 1cm; }}
            body {{ font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.6; }}
            .header {{ text-align: center; border-bottom: 3px solid #003366; padding-bottom: 10px; margin-bottom: 20px; }}
            .title {{ font-size: 22pt; color: #003366; font-weight: bold; }}
            .meta-box {{ background-color: #f4f4f4; border: 1px solid #ddd; padding: 10px; margin-bottom: 20px; border-radius: 5px; }}
            .topic-name {{ font-size: 14pt; font-weight: bold; }}
            h1 {{ color: #b30000; font-size: 18pt; border-left: 5px solid #b30000; padding-left: 10px; background-color: #fff5f5; }}
            h2 {{ color: #003366; font-size: 14pt; border-bottom: 1px solid #ccc; }}
            .bullet-point {{ margin-left: 20px; font-size: 11pt; }}
            .footer {{ position: absolute; bottom: 0; width: 100%; text-align: center; font-size: 9pt; color: #aaa; }}
        </style>
    </head>
    <body>
        <div class="header"><div class="title">STRUCTURED STUDY NOTES</div></div>
        <div class="meta-box"><span class="topic-name">Topic: {query}</span></div>
        <div class="content">{content}</div>
        <div class="footer">Generated by Gemma 4 Structured RAG</div>
    </body>
    </html>
    """

def format_ai_response_to_html(text):
    lines = text.split("\n")
    html_output = ""
    for line in lines:
        line = line.strip()
        if not line: continue
        if line.startswith("1.") or line.startswith("2.") or line.startswith("3.") or \
           line.startswith("4.") or line.startswith("5.") or line.startswith("6.") or line.startswith("7."):
            html_output += f"<h1>{line}</h1>"
        elif line.startswith("- ") or line.startswith("* "):
            html_output += f'<div class="bullet-point">• {line[2:]}</div>'
        else:
            html_output += f"<p>{line.replace('**', '<b>').replace('**', '</b>')}</p>"
    return html_output

def save_premium_pdf(content, filename, query):
    html_content = format_ai_response_to_html(content)
    full_html = get_html_template(html_content, query)
    full_path = os.path.join(OUTPUT_FOLDER, f"{filename}.pdf")
    with open(full_path, "wb") as pdf_file:
        pisa.CreatePDF(full_html, dest=pdf_file)
    return full_path

def generate_study_notes():
    embeddings = HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL_NAME)
    if not os.path.exists(DB_PATH): return
    vectorstore = Chroma(persist_directory=DB_PATH, embedding_function=embeddings)
    llm = Ollama(model=LLM_MODEL)

    print("\n--- 📝 Structured Note Builder ---")
    questions_input = input("Enter the topics/questions you want notes for (separated by commas): ")
    questions = [q.strip() for q in questions_input.split(",")]

    for query in questions:
        print(f"\n🚀 Processing: {query}...")
        
        # Retrieval
        docs = vectorstore.similarity_search(query, k=5)
        context = "\n\n---\n\n".join([doc.page_content for doc in docs])

        # The Ultimate Prompt
        prompt = f"""
        You are an expert academic writer. Your task is to create a highly structured study guide based on the provided context.
        
        STRICT FORMATTING REQUIREMENT:
        You must use the following 7-section structure exactly. Do not use any other headings.
        {STRUCTURE_TEMPLATE}
        
        CONTEXT:
        {context}
        
        TOPIC: {query}
        
        Write the notes now. Be thorough and professional.
        """

        response = llm.invoke(prompt)
        
        # Auto-generate filename based on query
        file_name = query.replace(" ", "_").replace("?", "")
        try:
            path = save_premium_pdf(response, file_name, query)
            print(f"✅ PDF Saved: {path}")
        except Exception as e:
            print(f"❌ Error saving {query}: {e}")

if __name__ == "__main__":
    generate_study_notes()
